import { POST_REQ_REQUIRED_PROPS } from "./request-handler.type";

export const POST_REQUEST_REQUIRED_PROPERTIES: POST_REQ_REQUIRED_PROPS[] = [
    POST_REQ_REQUIRED_PROPS.USERNAME,
    POST_REQ_REQUIRED_PROPS.AGE,
    POST_REQ_REQUIRED_PROPS.HOBBIES,
]